AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for deploying the task definition to be used by the scaler to start game servers

Parameters:
  ECSResourcesStackName: 
      Type: String
      Default: "fargate-game-servers-ecs-resources"
      Description: Name of the stack for the ECS resources to import
  Image: 
    Type: String
    Description: The url of the image to be used in the Task definition
  GameServerPort: 
    Description: "Port to be used by the game server"
    Type: Number
    Default: 1935

Resources:
  GameServerLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7
      LogGroupName: "fargate-game-servers"

  GameServerTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: / 
      Policies:
        - PolicyName: AmazonGameServerECSTaskRolePolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                # Allow Lambda invocation to access backend Lambda services
                - 'lambda:InvokeFunction'
              Resource: '*'

  GameServerTaskDefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      TaskRoleArn: !Ref GameServerTaskRole
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub "${ECSResourcesStackName}:ECSTaskExecutionRole"
      # 1 game server per Task
      ContainerDefinitions: 
        - 
          Name: "GameServer"
          Image: !Ref Image
          Environment:
          - Name: PORT
            Value: !Ref GameServerPort
          - Name: CONTAINERNAME
            Value: "container1"
          Cpu: 256
          Memory: 512
          PortMappings: 
            - 
              ContainerPort: !Ref GameServerPort
              HostPort: !Ref GameServerPort
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              "awslogs-group": "fargate-game-servers"
              "awslogs-region": !Ref AWS::Region
              "awslogs-stream-prefix": "ecs"                                                                                                         

Outputs:
  TaskDefinition:
    Description: The task definition resource
    Value: !Ref GameServerTaskDefinition
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'TaskDefinition' ] ]